version: '3.8'
services:
  odoo-web:
    build: .
    env_file:
      - .env
    container_name: odoo_${MODE}
    image: odoo:16
    restart: always
    ports:
      - "${ODOO_PORT}:8069"
    depends_on:
      - postgres
    volumes:
      - ./config/:/etc/odoo
      - ./addons/:/mnt/extra-addons
    environment:
      - HOST=${ODOO_HOST}
      - USER=${ODOO_USER}
      - PASSWORD=${ODOO_PASSWORD}

  postgres:
    container_name: postgres_${MODE}
    image: postgres:16
    restart: always
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data/pgdata

volumes:
  postgres-db-volume:

